#!/usr/bin/env python3
"""
trace-analyze.py
Analyze traces generated by trace-gen.py

Examples:
  ./trace-analyze.py traces/run1.json
  ./trace-analyze.py traces/run1.json --csv concurrency.csv
  ./trace-analyze.py traces/run1.json --plot

Outputs:
 - Summary statistics for arrivals and durations
 - Peak concurrent sessions and time(s)
 - Optional CSV with concurrency timeline
 - Optional plots (requires matplotlib)
"""
import argparse
import json
import math
import statistics
from datetime import timedelta
import sys

try:
    import matplotlib.pyplot as plt
    HAS_MPL = True
except Exception:
    HAS_MPL = False


def percentile(data, p):
    if not data:
        return None
    k = (len(data) - 1) * (p / 100.0)
    f = math.floor(k)
    c = math.ceil(k)
    if f == c:
        return data[int(k)]
    d0 = data[int(f)] * (c - k)
    d1 = data[int(c)] * (k - f)
    return d0 + d1


def analyze_trace(trace):
    ues = trace.get("ues", [])
    arrivals = []
    durations = []
    for ue in ues:
        a = ue.get("arrival_s")
        d = ue.get("duration_s")
        if a is None or d is None:
            continue
        arrivals.append(float(a))
        durations.append(float(d))

    arrivals.sort()
    durations.sort()

    summary = {}
    n = len(arrivals)
    summary["num_ues"] = n
    if n == 0:
        return summary

    first = arrivals[0]
    last = arrivals[-1]
    span = last - first if last > first else 0.0

    summary["arrival_first_s"] = first
    summary["arrival_last_s"] = last
    summary["arrival_span_s"] = span
    summary["arrival_mean_s"] = statistics.mean(arrivals)
    summary["arrival_std_s"] = statistics.pstdev(arrivals) if n > 1 else 0.0
    summary["arrival_rate_empirical_per_s"] = n / (span if span > 0 else 1.0)

    # inter-arrival stats
    inter = [arrivals[i] - arrivals[i - 1] for i in range(1, n)] if n > 1 else []
    if inter:
        summary["inter_mean_s"] = statistics.mean(inter)
        summary["inter_std_s"] = statistics.pstdev(inter) if len(inter) > 1 else 0.0
        summary["inter_min_s"] = min(inter)
        summary["inter_max_s"] = max(inter)
    else:
        summary["inter_mean_s"] = summary["inter_std_s"] = summary["inter_min_s"] = summary["inter_max_s"] = None

    # duration stats
    if durations:
        summary["dur_mean_s"] = statistics.mean(durations)
        summary["dur_std_s"] = statistics.pstdev(durations) if len(durations) > 1 else 0.0
        summary["dur_min_s"] = durations[0]
        summary["dur_max_s"] = durations[-1]
        summary["dur_p50_s"] = percentile(durations, 50)
        summary["dur_p90_s"] = percentile(durations, 90)
        summary["dur_p95_s"] = percentile(durations, 95)
        summary["dur_p99_s"] = percentile(durations, 99)
    else:
        summary.update({k: None for k in ["dur_mean_s", "dur_std_s", "dur_min_s", "dur_max_s", "dur_p50_s", "dur_p90_s", "dur_p95_s", "dur_p99_s"]})

    # concurrency timeline: events (time, delta)
    events = []
    for a, d in zip(arrivals, durations):
        events.append((a, 1))
        events.append((a + d, -1))
    events.sort(key=lambda x: (x[0], -x[1]))  # ensure arrivals (+1) come before departures at same time

    concurrency = 0
    peak = 0
    peak_times = []
    timeline = []  # (time, concurrency) at change points
    for t, delta in events:
        concurrency += delta
        timeline.append((t, concurrency))
        if concurrency > peak:
            peak = concurrency
            peak_times = [t]
        elif concurrency == peak:
            peak_times.append(t)

    summary["peak_concurrency"] = peak
    summary["peak_times_s"] = peak_times
    summary["timeline"] = timeline
    return summary


def print_summary(summary):
    if not summary:
        print("No data to summarize.")
        return
    print("Trace summary:")
    print(f"  Number of UEs: {summary.get('num_ues', 0)}")
    if summary.get("num_ues", 0) == 0:
        return
    print(f"  Arrivals: first={summary['arrival_first_s']:.3f}s last={summary['arrival_last_s']:.3f}s span={summary['arrival_span_s']:.3f}s")
    print(f"  Arrival mean={summary['arrival_mean_s']:.6f}s std={summary['arrival_std_s']:.6f}s empirical_rate={summary['arrival_rate_empirical_per_s']:.6f}/s")
    if summary.get('inter_mean_s') is not None:
        print(f"  Inter-arrival: mean={summary['inter_mean_s']:.6f}s std={summary['inter_std_s']:.6f}s min={summary['inter_min_s']:.6f}s max={summary['inter_max_s']:.6f}s")
    if summary.get('dur_mean_s') is not None:
        print(f"  Durations: mean={summary['dur_mean_s']:.6f}s std={summary['dur_std_s']:.6f}s min={summary['dur_min_s']:.6f}s max={summary['dur_max_s']:.6f}s")
        print(f"    p50={summary['dur_p50_s']:.6f}s p90={summary['dur_p90_s']:.6f}s p95={summary['dur_p95_s']:.6f}s p99={summary['dur_p99_s']:.6f}s")
    print(f"  Peak concurrency: {summary['peak_concurrency']}")
    if summary['peak_times_s']:
        # print up to a few peak times
        pts = summary['peak_times_s']
        shown = pts[:5]
        s = ', '.join(f"{t:.3f}s" for t in shown)
        if len(pts) > 5:
            s += f", ... (+{len(pts)-5} more)"
        print(f"  Peak time(s): {s}")


def write_csv_timeline(timeline, outpath):
    import csv
    with open(outpath, "w", newline='') as f:
        w = csv.writer(f)
        w.writerow(["time_s", "concurrency"])
        for t, c in timeline:
            w.writerow([f"{t:.6f}", c])
    print(f"Wrote concurrency timeline CSV to {outpath}")


def plot_histograms(arrivals, durations):
    if not HAS_MPL:
        print("matplotlib not available; cannot plot. Install matplotlib to enable plotting.")
        return
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    axes[0].hist(arrivals, bins=50)
    axes[0].set_title('Arrival times')
    axes[0].set_xlabel('time (s)')
    axes[1].hist(durations, bins=50)
    axes[1].set_title('Session durations (s)')
    axes[1].set_xlabel('duration (s)')
    plt.tight_layout()
    plt.show()


def main():
    p = argparse.ArgumentParser(description="Analyze traces produced by trace-gen.py")
    p.add_argument("trace", help="Path to trace JSON file")
    p.add_argument("--csv", help="Write concurrency timeline CSV to this path")
    p.add_argument("--plot", action="store_true", help="Show simple histograms (requires matplotlib)")
    args = p.parse_args()

    try:
        with open(args.trace) as f:
            trace = json.load(f)
    except Exception as e:
        print(f"Failed to open/parse trace file: {e}")
        sys.exit(2)

    summary = analyze_trace(trace)
    print_summary(summary)

    if args.csv and summary.get("timeline"):
        write_csv_timeline(summary["timeline"], args.csv)

    if args.plot:
        ues = trace.get("ues", [])
        arrivals = [float(ue.get("arrival_s")) for ue in ues if ue.get("arrival_s") is not None]
        durations = [float(ue.get("duration_s")) for ue in ues if ue.get("duration_s") is not None]
        plot_histograms(arrivals, durations)


if __name__ == "__main__":
    main()
